[package]
name = "simpletel"
version = "0.0.1"
edition = "2021"
description = "simple rust app demo for opentel"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rand = "0.8.5"

elasticsearch = "8.5.0-alpha.1"
serde_json = "1.0"


